version: '3'
services:
db:
image: mariadb:latest
volumes:
- /tmp/dc-test-db:/var/lib/mysql
ports:
- "3306:3306"
environment:
MYSQL_ROOT_PASSWORD: 030119070
restart: always
wordpress:
image: wordpress:latest
volumes:
- /tmp/dc-test-wordpress:/var/www/html
ports:
- "8082:80"
environment:
WORDPRESS_DB_HOST: db:3306
WORDPRESS_DB_PASSWORD: geheim
restart: on-failure

